services:

  Visol\Migrations\Command\DoctrineDumpCommand:
    tags:
      - name: 'console.command'
        command: 'migrations:dump'
        schedulable: false

  Visol\Migrations\Command\DoctrineExecuteCommand:
    tags:
      - name: 'console.command'
        command: 'migrations:execute'
        schedulable: false

  Visol\Migrations\Command\DoctrineGenerateCommand:
    tags:
      - name: 'console.command'
        command: 'migrations:generate'
        schedulable: false

  Visol\Migrations\Command\DoctrineLatestCommand:
    tags:
      - name: 'console.command'
        command: 'migrations:latest'
        schedulable: false

  Visol\Migrations\Command\DoctrineListCommand:
    tags:
      - name: 'console.command'
        command: 'migrations:list'
        schedulable: false

  Visol\Migrations\Command\DoctrineMigrateCommand:
    tags:
      - name: 'console.command'
        command: 'migrations:migrate'
        schedulable: false

  Visol\Migrations\Command\DoctrineRollupCommand:
    tags:
      - name: 'console.command'
        command: 'migrations:rollup'
        schedulable: false

  Visol\Migrations\Command\DoctrineStatusCommand:
    tags:
      - name: 'console.command'
        command: 'migrations:status'
        schedulable: false

  Visol\Migrations\Command\DoctrineVersionCommand:
    tags:
      - name: 'console.command'
        command: 'migrations:version'
        schedulable: false
